"""Base class for label generators.

All label generators inherit from ``BaseLabelGenerator`` which defines:
    - A consistent ``generate()`` interface
    - Time-safety guarantees (labels use only *future* shifts — they are
      intended to be used as *targets*, not *features*)
    - Structured logging via ``structlog``

Important time-safety note:
    Labels are generated by shifting **forward** (``shift(-N)``).  The last
    ``N`` rows will therefore contain ``NaN`` — these rows must be dropped
    before training.  At inference time, labels are **not** available; they
    are prediction targets.
"""

from __future__ import annotations

import abc
from typing import List

import pandas as pd

from src.utils.logging import get_logger

logger = get_logger(__name__)


class BaseLabelGenerator(abc.ABC):
    """Abstract base class for all label generators.

    Sub-classes must implement:
        - ``name``  (property) -> unique identifier such as ``cls_1d_updown``
        - ``label_columns`` (property) -> list of column names produced
        - ``_compute(df)`` -> add label columns in-place and return ``df``

    Usage::

        gen = Cls1dUpDown(threshold=0.01)
        df = gen.generate(ohlcv_df)
    """

    # ── Public API ────────────────────────────────────────────

    def generate(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add label columns to *df* and return a copy.

        Args:
            df: DataFrame containing at least ``close`` (and ``volume``/
                ``high``/``low`` for some generators).  Must be sorted
                ascending by date.

        Returns:
            A *copy* of ``df`` with the new label column(s) appended.
            The last ``horizon`` rows will contain ``NaN`` in the label
            column(s); drop them before training.
        """
        self._validate(df)
        out = df.copy()
        out = self._compute(out)

        logger.info(
            "label_generated",
            label=self.name,
            columns=self.label_columns,
            rows_total=len(out),
            rows_valid=int(out[self.label_columns[0]].notna().sum()),
        )
        return out

    # ── Abstract interface ────────────────────────────────────

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Unique identifier for this label (e.g. ``cls_1d_updown``)."""
        ...

    @property
    @abc.abstractmethod
    def label_columns(self) -> List[str]:
        """List of column names produced by this generator."""
        ...

    @abc.abstractmethod
    def _compute(self, df: pd.DataFrame) -> pd.DataFrame:
        """Compute the label and add column(s) to *df* in-place."""
        ...

    # ── Shared validation ─────────────────────────────────────

    def _validate(self, df: pd.DataFrame) -> None:
        """Check that required source columns exist."""
        required = {"close"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"[{self.name}] Missing required columns: {missing}"
            )
        if df.empty:
            raise ValueError(f"[{self.name}] DataFrame is empty")
