"""Pydantic response schemas — enforces the JSON API contract.

These models define the exact output structure of the prediction endpoint.
All field names match the contract specification from Phase 2 requirements.
"""

from __future__ import annotations

import datetime as dt

from pydantic import BaseModel, Field


# ── Nested schema components ──────────────────────────────────


class TrendProbabilities(BaseModel):
    """Probability vector from Model A (XGBoost Trend Classifier)."""

    up: float = Field(..., ge=0.0, le=1.0, description="Probability of uptrend (>+2%)")
    down: float = Field(..., ge=0.0, le=1.0, description="Probability of downtrend (<-2%)")
    sideways: float = Field(..., ge=0.0, le=1.0, description="Probability of sideways (±2%)")


class ExpectedRange(BaseModel):
    """Quantile price range from Model B (LightGBM Range Regressor)."""

    bottom_10th: float = Field(..., description="10th percentile — support floor")
    median_50th: float = Field(..., description="50th percentile — median expectation")
    ceiling_90th: float = Field(..., description="90th percentile — resistance ceiling")


class ActionPlan(BaseModel):
    """Trading action derived from combined model outputs."""

    recommendation: str = Field(
        ...,
        description="Action: BUY, SELL, RANGE_TRADE, STAND_ASIDE",
    )
    entry_zone: list[float] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="[lower_bound, upper_bound] entry price range",
    )
    stop_loss: float = Field(..., description="Stop-loss price level")
    take_profit: float = Field(..., description="Take-profit price level")


class QuantitativeSignals(BaseModel):
    """Combined quantitative analysis from both ML models."""

    trend_probabilities: TrendProbabilities
    expected_range: ExpectedRange
    action_plan: ActionPlan


class ConfidenceMetrics(BaseModel):
    """Confidence routing — different confidence levels by data source."""

    stock_quantitative_data: float = Field(
        default=0.95,
        description="Confidence for model-derived stock data (always 0.95)",
    )
    general_market_context: float = Field(
        default=0.70,
        description="Confidence for contextual/metadata info (always 0.70)",
    )


class SystemParameters(BaseModel):
    """Enforced system constraints for downstream consumers (LLM / Phase 3)."""

    max_risk_tolerance: float = Field(
        ...,
        le=0.70,
        description="Risk cap — always ≤ 0.70 regardless of input",
    )
    confidence_metrics: ConfidenceMetrics


class MainRisk(BaseModel):
    """Specific risk identified by the Analyst."""
    risk_type: str = Field(..., description="macro, legal, financial, or operational")
    description: str
    zone: str | None = None

class QualitativeSignalEvidence(BaseModel):
    """Evidence linked to a specific zone."""
    evidence: str
    zone: str

class QualitativeSignals(BaseModel):
    """Bulish and bearish signals with evidence."""
    bullish: list[QualitativeSignalEvidence]
    bearish: list[QualitativeSignalEvidence]

class DeepLearningContext(BaseModel):
    """Context from Phase 10 Deep Learning models (TFT & CNN)."""
    tft_forecast: str | None = Field(default=None, description="TFT Sequence forecast summary")
    cnn_microstructure: str | None = Field(default=None, description="CNN LOB microstructure summary")

class RLRecommendation(BaseModel):
    """Context from Phase 10 RL Portfolio Manager (PPO)."""
    suggested_allocation_pct: float | None = Field(default=None, ge=0.0, le=0.70)
    justification: str | None = Field(default=None)

class QualitativeAnalysis(BaseModel):
    """Phase 3 qualitative analysis output generated by the Risk Analyst Engine."""

    analysis_status: str = Field(..., description="success or insufficient_data")
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    veto_flag: bool = Field(default=False)
    overall_outlook: str | None = Field(default=None, description="positive, negative, or neutral")
    reasoning: str = Field(..., description="Summary of the analysis.")
    signals: QualitativeSignals | None = None
    deep_learning_context: DeepLearningContext | None = Field(default=None)
    rl_recommendation: RLRecommendation | None = Field(default=None)
    main_risks: list[MainRisk] | None = None
    anti_hallucination_check_passed: bool = Field(default=True)


# ── Phase 4: Final Execution Schemas ─────────────────────────


class MatrixConsensus(BaseModel):
    """Output of the Decision Matrix matching ML and LLM signals."""

    ml_signal: str = Field(..., description="BUY, SELL, RANGE_TRADE, STAND_ASIDE")
    llm_sentiment: str = Field(..., description="positive, neutral, negative, N/A")
    veto_triggered: bool = Field(..., description="True if LLM vetoed an ML signal")


class RiskManagementOverride(BaseModel):
    """Records how the engine mutated the ML suggestions based on constraints."""

    original_stop_loss_pct: float
    applied_stop_loss_pct: float
    fomo_check_passed: bool


class OrderPayload(BaseModel):
    """The final actionable payload ready to be sent to a broker."""

    order_type: str = Field(..., description="LIMIT, MARKET, etc.")
    entry_price: float
    volume: int
    hard_stop_loss_price: float
    take_profit_price: float


# ── Top-level response models ────────────────────────────────


class PredictionResponse(BaseModel):
    """Full prediction response — the JSON API contract.

    Example::

        {
            "ticker": "SSI",
            "timestamp": "2026-03-15T14:15:00Z",
            "quantitative_signals": { ... },
            "qualitative_analysis": { ... },  # Present if /analyze is called
            "system_parameters": { ... }
        }
    """

    ticker: str = Field(..., description="Stock symbol")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp")
    quantitative_signals: QuantitativeSignals
    qualitative_analysis: QualitativeAnalysis | None = Field(default=None)
    system_parameters: SystemParameters


class FinalExecutionResponse(BaseModel):
    """The final Phase 4 output payload after risk management and LLM consensus."""

    order_id: str
    ticker: str
    execution_decision: str = Field(
        ...,
        description="EXECUTE_BUY, EXECUTE_SELL, CANCEL_ORDER, STANDBY",
    )
    matrix_consensus: MatrixConsensus
    risk_management_override: RiskManagementOverride | None = None
    order_payload: OrderPayload | None = None
    system_confidence: dict[str, float]


# ── Request / utility models ─────────────────────────────────


class TrainRequest(BaseModel):
    """Request body for training endpoint."""

    ticker: str = Field(..., description="Stock ticker to train models for")
    use_mock: bool = Field(
        default=False,
        description="Use synthetic mock data instead of database",
    )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = "ok"
    version: str = "2.0.0"
    phase: str = "Phase 2 — Quantitative ML Pipeline"


class TrainResponse(BaseModel):
    """Training result response."""

    ticker: str
    status: str
    metrics: dict


# ── Chat Endpoint Schemas ─────────────────────────────────────


class ChatMessage(BaseModel):
    """A single chat message."""

    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """Request body for the conversational endpoint."""

    messages: list[ChatMessage] = Field(..., description="Chat history")
    ticker: str | None = Field(default=None, description="Optional focus ticker")


class ChatResponse(BaseModel):
    """Response from the conversational endpoint."""

    response: str
    context_used: list[str] = Field(default_factory=list)

