"""Pydantic response schemas for the diagnostic research API."""

from __future__ import annotations

import datetime as dt
from typing import Any

from pydantic import BaseModel, Field


# --- Internal quantitative components retained for legacy engine compatibility ---


class TrendProbabilities(BaseModel):
    """Probability vector from the trend classifier."""

    up: float = Field(..., ge=0.0, le=1.0, description="Probability of uptrend")
    down: float = Field(..., ge=0.0, le=1.0, description="Probability of downtrend")
    sideways: float = Field(..., ge=0.0, le=1.0, description="Probability of sideways movement")


class ExpectedRange(BaseModel):
    """Quantile price range from the range regressor."""

    bottom_10th: float = Field(..., description="10th percentile range floor")
    median_50th: float = Field(..., description="50th percentile range midpoint")
    ceiling_90th: float = Field(..., description="90th percentile range ceiling")


class ActionPlan(BaseModel):
    """Internal legacy route label used by engine tests and non-public adapters."""

    recommendation: str = Field(
        ...,
        description="Internal legacy route label; not a public API authority field.",
    )
    entry_zone: list[float] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Internal model price range candidate",
    )
    stop_loss: float = Field(..., description="Internal downside-control reference")
    take_profit: float = Field(..., description="Internal upside-range reference")


class QuantitativeSignals(BaseModel):
    """Combined quantitative analysis from both ML models."""

    trend_probabilities: TrendProbabilities
    expected_range: ExpectedRange
    action_plan: ActionPlan


class ConfidenceMetrics(BaseModel):
    """Confidence routing by data source."""

    stock_quantitative_data: float = Field(
        default=0.95,
        description="Confidence for model-derived stock data",
    )
    general_market_context: float = Field(
        default=0.70,
        description="Confidence for contextual metadata",
    )


class SystemParameters(BaseModel):
    """Enforced system constraints for downstream diagnostics."""

    max_risk_tolerance: float = Field(
        ...,
        le=0.70,
        description="Risk cap, always at or below 0.70 regardless of input",
    )
    confidence_metrics: ConfidenceMetrics


class MainRisk(BaseModel):
    """Specific risk identified by the analyst engine."""

    risk_type: str = Field(..., description="macro, legal, financial, or operational")
    description: str
    zone: str | None = None


class QualitativeSignalEvidence(BaseModel):
    """Evidence linked to a specific zone."""

    evidence: str
    zone: str


class QualitativeSignals(BaseModel):
    """Bullish and bearish evidence groups."""

    bullish: list[QualitativeSignalEvidence]
    bearish: list[QualitativeSignalEvidence]


class DeepLearningContext(BaseModel):
    """Context from deep learning models."""

    tft_forecast: str | None = Field(default=None, description="TFT sequence forecast summary")
    cnn_microstructure: str | None = Field(default=None, description="CNN microstructure summary")


class RLRecommendation(BaseModel):
    """Internal RL diagnostic context retained for legacy parser compatibility."""

    suggested_allocation_pct: float | None = Field(default=None, ge=0.0, le=0.70)
    justification: str | None = Field(default=None)


class QualitativeAnalysis(BaseModel):
    """Qualitative risk analysis output generated by the analyst engine."""

    analysis_status: str = Field(..., description="success or insufficient_data")
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    veto_flag: bool = Field(default=False)
    overall_outlook: str | None = Field(default=None, description="positive, negative, or neutral")
    reasoning: str = Field(..., description="Summary of the analysis.")
    signals: QualitativeSignals | None = None
    deep_learning_context: DeepLearningContext | None = Field(default=None)
    rl_recommendation: RLRecommendation | None = Field(default=None)
    main_risks: list[MainRisk] | None = None
    anti_hallucination_check_passed: bool = Field(default=True)


# --- Internal matrix/risk compatibility models ---


class MatrixConsensus(BaseModel):
    """Output of the internal matrix compatibility layer."""

    ml_signal: str = Field(..., description="Internal model route label")
    llm_sentiment: str = Field(..., description="positive, neutral, negative, or N/A")
    veto_triggered: bool = Field(..., description="True if qualitative risk vetoed a model lane")
    consensus_score: float = Field(default=0.0, description="Weighted numeric score")


class RiskManagementOverride(BaseModel):
    """Records internal risk-bound adjustments."""

    original_stop_loss_pct: float
    applied_stop_loss_pct: float
    fomo_check_passed: bool


class OrderPayload(BaseModel):
    """Internal risk sizing candidate retained outside governed API responses."""

    order_type: str = Field(..., description="Internal route type label")
    entry_price: float
    volume: int
    hard_stop_loss_price: float
    take_profit_price: float


# --- Governed public response models ---


class PredictionResponse(BaseModel):
    """Diagnostic prediction/analysis response."""

    ticker: str = Field(..., description="Stock symbol")
    timestamp: str | dt.datetime = Field(..., description="ISO-8601 UTC timestamp")
    technical: dict[str, Any]
    sentiment: dict[str, Any] | None = None
    fusion: dict[str, Any] | None = None
    risk: dict[str, Any] | None = None
    run_id: str
    status: str = "success"
    candidate_status: str = "diagnostic_only"
    review_required: bool = True
    diagnostic_plan: list[str] = Field(default_factory=list)
    non_authoritative_summary: str = (
        "Research diagnostics only; not financial advice or account-routing authority."
    )
    data_provenance: dict[str, Any] = Field(default_factory=dict)


class LegacyRouteDiagnosticResponse(BaseModel):
    """Response used by retained legacy/demo routes."""

    route_id: str
    ticker: str | None = None
    status: str
    candidate_status: str
    diagnostic_signal: str
    route_decision: str
    decision_lane: str
    risk_flag: str
    review_required: bool = True
    diagnostic_summary: str
    diagnostic_plan: list[str] = Field(default_factory=list)
    data_provenance: dict[str, Any] = Field(default_factory=dict)


# --- Request / utility models ---


class TrainRequest(BaseModel):
    """Request body for training endpoint."""

    ticker: str = Field(..., description="Stock ticker to train models for")
    use_mock: bool = Field(
        default=False,
        description="Use synthetic mock data instead of database",
    )
    runtime_mode: str = Field(
        default="research",
        description="Runtime mode: demo, research, or audit",
    )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = "ok"
    version: str = "2.0.0"
    phase: str = "Diagnostic research API"


class TrainResponse(BaseModel):
    """Training result response."""

    ticker: str
    status: str
    metrics: dict
    data_provenance: dict[str, Any] = Field(default_factory=dict)


# --- Chat endpoint schemas ---


class ChatMessage(BaseModel):
    """A single chat message."""

    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """Request body for the conversational endpoint."""

    messages: list[ChatMessage] = Field(..., description="Chat history")
    ticker: str | None = Field(default=None, description="Optional focus ticker")


class ChatResponse(BaseModel):
    """Response from the conversational endpoint."""

    response: str
    context_used: list[str] = Field(default_factory=list)
